### ISSUE TITLE
Why are you using the CustomType class and register it as qml type ?

### ISSUE THREAD

**Issue by Dravigon** [hvoigt/qt-qml-treeview#1]
Without the custom type class the program seems to run fine any reasons why as to use it?

**Comment by hvoigt** [comment]
@Dravigon: Sorry for replying so late. This got buried in the notifications of other projects which are quite active. Next time please mention my name with @hvoigt, that should get me an email notification.

Did you see the last commit in the repository? https://github.com/hvoigt/qt-qml-treeview/commit/b0b8b9d949db3bf407535fc85ea35b42d37d908c

There is an explanation in there... Basically I did this for demonstration purposes, since I needed to transport more than one value in my private project. This seems to be a nice way to do so. And as a reference for myself I put it here :)

P.S.: If you checkout the code before that commit you get it without the custom type.

**Comment by hvoigt** [comment]
Closing this as this is not a real issue and there seems to be no discussions needs left.

**Comment by Dravigon** [comment]
got it bro thanks
